- notifications/notifications.py
* All notifications that don't have reason "mention" are marked as read
* This is intended to include notifications generated by things like
the prow bots
* This is an attempt to bring back sanity to notifications by allowing people
to see more valuable notifications at http://github.com/notifications
* The reason for checking this in is to begin to provide some sample code
for how we might begin to build a more sophisticated applications for doing
this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/code-intelligence/13)
> Create a simple python program to mark notifications as read.

- Issue-Embeddings/flask_app/inference.py
- Issue-Embeddings/notebooks/04b_Inference-Batch.ipynb
This will allow us to onboard new repos in a much more realistic timeframe and will be a much better user experience, especially for massive orgs like Kubernetes.
This was done by taking the following steps:
- Hacking the machinery of fastai datablock api to perform multi-threaded transformation for inference (there isn't an easy way out of the box to do this)
- Sorting Issues by their sequence lengths before generating batches to minimize the amount of padding necessary in each batch.
- Batching the issues together (previously we were performing inference on one issue at a time). 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/code-intelligence/30)
> Speedup Inference (to get Embeddings for training & new repo on-boarding) by 10x

- Label_Microservice/notebooks/repo_mlp.ipynb
- Label_Microservice/requirements.txt
- Label_Microservice/tests/test_mlp.py
- Label_Microservice/tests/test_worker.py
- py/code_intelligence/embeddings.py
- py/code_intelligence/github_app.py
- py/code_intelligence/github_util.py
- py/label_microservice/mlp.py
- py/label_microservice/repo_config.py
- py/label_microservice/worker.py
Design worker class
- allow mlpwrapper to load classifier from file
- add github util and app class
- add worker class to address pubsub event and do label prediction
- use fire to create entry point for worker
- update requirements.txt
- update embeddings to return issues even though they haven't been labeled
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/code-intelligence/41)
> Add worker class to address events in pubsub

- py/label_microservice/repo_config.py
We only use repo owner and repo name to set all paths including local and gcs.
This PR cleans up my original testing code which is unnecessary such as downloading yaml from gcs (and then set the path).
For all other configs which need to be set in `/.github/issue_label_bot.yaml`, we will call `code_intelligence.github_util.get_yaml` instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/code-intelligence/43)
> Clean up RepoConfig

- py/label_microservice/worker.py
This PR adds exception handling to the `callback` function in workers.
If there is any unexpected error, use the exception handling to log the error message and still acknowledge the message in Pub/Sub.
If there is an error and the worker does not acknowledge the message, the error will kill all pods that workers are running in because the message will be delivered to them sequentially.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/code-intelligence/44)
> Add exception handling to worker.py

- py/code_intelligence/embeddings.py
- py/code_intelligence/inference.py
This PR is to check in the code using batching inference and fix error while doing batch inference.
The reason to update `inference.py` is that when we use batches, it may encounter CUDA out of memory error in the last few iterations because the distribution of the lengths of sentences may be a long tail.
I update the batch strategy to fix it. If the current batch causes the cuda out of memory error, the batch size will decrease to half of the original size.
/assign @jlewi 
/assign @zhenghuiwang 
/assign @hamelsmu
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/code-intelligence/53)
> Check in the batch code.

- .github/workflows/build_image.yaml
- .github/workflows/triage_issues.yaml
- Issue_Triage/action/README.md
- Issue_Triage/action/action.yml
* Instead of storing the image in a personal account we should use the kubeflow
organization.
* Update the issue_triage.yaml workflow in this repository to use the master version of the action
* Related to kubeflow/code-intelligence#66
* Related to kubeflow/community#27 - GitHub action for adding issues to triage
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/code-intelligence/67)
> Use the Kubeflow DockerHub organization for the GitHub action for issue_triage

- py/label_microservice/combined_model.py
- py/label_microservice/combined_model_test.py
- py/label_microservice/issue_label_predictor.py
- py/label_microservice/models.py
- py/label_microservice/repo_specific_model.py
- py/label_microservice/repo_specific_model_test.py
- py/label_microservice/test_util.py
- py/label_microservice/universal_kind_label_model.py
* To combine multiple models we define a base class IssueLabelModel
that defines a common interface for all the models.
* This way different models can just implement that interface and we
can easily combine the results.
* UniveralKindLabelModel will be used for the generic model to predict
label kind that is trained on all repositories.
* The UniversalKindLabelModel class is based on the IssueLabeler code
https://github.com/machine-learning-apps/Issue-Label-Bot/blob/536e8bf4928b03d522dd021c0464587747e90a87/flask_app/utils.py#L67
* repo_specific_model.py contains a model class for predicting labels
using a repo specific model.
* Most of the code was previously inside worker.py
* We wrap this code in the newly defined model interface so we can easily
combine different models.
* Subsequent …
> Define classes to combine repository specific labels with the universal model for issue kind

- py/code_intelligence/run_with_auto_restart.py
* Related to kubeflow/code-intelligence#78 - Speedup development using
skaffold file sync
* Skaffold can auto sync python files to a deployed container skipping the
expensive image rebuilding and deployment steps.
* However, for that to work we need to restart our program when the files
change.
* We can't rely on Flask's autoreloader because some of our models interact
poorly with Flask's debug mode.
* This is a simple python program that launches another program in a subprocess.
The program will also watch directories an automatically restart the
subprocess if any file changes are detected.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/code-intelligence/81)
> Create an auto-restarter for use with skaffold.

- py/code_intelligence/run_with_auto_restart.py
- py/code_intelligence/util.py
- py/label_microservice/combined_model.py
- py/label_microservice/issue_label_predictor.py
- py/label_microservice/models.py
- py/label_microservice/repo_specific_model.py
- py/label_microservice/universal_kind_label_model.py
- py/label_microservice/worker.py
* worker.py should format logs as json entries. This will make it easier
to query the data in BigQuery and stackdriver to measure performance.
* Related to #79
* To deal with workload identity flakiness (#88) test that we can get
application default credentials on startup and if not exit.
* As a hack to deal with multi-threading issues with Keras models (#89)
have the predict function load a new model on each call
* It looks like the way pubsub works there is actually a thread pool
so predict calls won't be handled in the same thread even though
we throttle it to handle one item at a time.
Related to #70: Ensemble models
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/code-intell …
> Structured logging and other bug fixes.

- Issue_Triage/README.md
- Issue_Triage/requirements.txt
* Related to: #96 action is failing with import error
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/code-intelligence/97)
> Add pytz to the requirements for the GitHub triage action image.

- Issue_Triage/requirements.txt
because it is used by the util package.
Related to: kubeflow/code-intelligence#96 issue triage action failing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/code-intelligence/98)
> Need to include the json log formatter in the issue triage action image

- .github/issue_label_bot.yaml
- .gitignore
* We want the label bot to use the label "kind/feature" for feature issues
* Update the .gitignore file with some paths.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/code-intelligence/94)
> label bot config should alias feature -> kind/feature

- Label_Microservice/deployment/overlays/dev/kustomization.yaml
- Label_Microservice/deployment/overlays/prod/kustomization.yaml
- py/label_microservice/worker.py
Use json logging to log information about the issue being processed when exceptions occur
related to: kubeflow/code-intelligence#70 Combine repo specific and universal model
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/code-intelligence/77)
> Use json logging to log information about the issue being processed when exceptions occur

- Issue_Triage/notebooks/metrics.ipynb
* The statics are based off data logged by the worker. The logs are
dumped into BigQuery.
* We use the logs to compute statistics about how many issues were
assigned a kind, area, or platform label. This gives us a good
proxy for the amount of toil saved.
* Include a plot of the number of issues per day.
Related to #71: Notebook to compute issue stats
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/code-intelligence/111)
> Create a notebook to compute stats about label bot.

- py/code_intelligence/github_app.py
- py/code_intelligence/graphql.py
* Create classes to make it easier to interchange the use of personal access
tokens and GitHub app tokens.
* Create an abstract class to wrap a token that can be injected into client
librabries like GraphQL
* Authenticating using GitHub App's has the following important differences
compared to personal access tokens
1. The tokens expire
2. GitHub App tokens must be scoped to a specific repository or organization
installation id
* We solve these problems as follows
1. The GitHubAppTokenGenerator automatically refreshes credentials
2. The GitHubAppTokenGenerator can be instantiated with the
repository for which to get the installation id
3. We add to GitHubApp caching of installation ids
4. We modify GraphQL.run_query to take a function to generate the auth headers
* We need to pass the …
> Create token getter classes for GitHub.

- Issue_Embeddings/notebooks/01_AcquireData.ipynb
- Issue_Embeddings/notebooks/02_fastai_DataBunch.ipynb
- Issue_Embeddings/notebooks/03_Create_Model.ipynb
- Issue_Embeddings/notebooks/07_Get_Repo_TrainingData_BigQuery.ipynb
- Issue_Embeddings/notebooks/Get-GitHub-Issues.ipynb
- Issue_Embeddings/requirements.txt
- Issue_Triage/notebooks/metrics.ipynb
- Issue_Triage/notebooks/triage.ipynb
- Label_Microservice/notebooks/issues_loader.ipynb
- docs/train_kubeflow_label_model.md
- py/code_intelligence/embeddings.py
- py/code_intelligence/gcs_util.py
- py/code_intelligence/util.py
Compute embeddings for all kubeflow repositories.
* This is the first step in creating an org wide model for all of Kubeflow (#110)
* Modify the Get-GitHub-Issues.ipynb model to reuse code in the embeddings directory.
* Add some missing packages to requirements.txt.
* Use the GitHub graphql client to get a list of all repositories.
* Add some missing GCS utilities
* Remove some of the duplication between Get-GitHub-Issues.ipynb and our
library methods (#122)
* Start fetching the data from bigquery.
* Using BigQuery turned out to be a lot better for bulk pulling all
of the Kubeflow issues.
* Use hdf5 to save the data.
* Start a doc to keep track of notes for how to train a Kubeflow model. Add logic to save to hDF5 and do 
a sanity check compared to the inference code
* Add a function to …
> Compute embeddings for all kubeflow repositories.

- Label_Microservice/.build/prod/extensions_v1beta1_deployment_label-bot-worker.yaml
- Label_Microservice/README.md
- Label_Microservice/deployment/overlays/prod/kustomization.yaml
- py/code_intelligence/embeddings.py
- py/code_intelligence/github_util.py
- py/code_intelligence/util.py
- py/code_intelligence/util_test.py
- py/label_microservice/automl_model.py
- py/label_microservice/cli.py
- py/label_microservice/issue_label_predictor.py
- py/label_microservice/worker.py
* As described in kubeflow/code-intelligence#133 as people comment on
an issue; label bot should take these additional comments into
account when predicting labels.
* Hopefully these additional comments will lead to better predictions
as they will contain valuable information.
To support this:
* get_issue should get all comments (not just the body)
* We also need to get any labels that have been explicitly removed as well as
any labels already on the issue.
We need this because we want to take into account multiple comments
and not just the first one when predicting labels.
* Since we are going to add additional labels based on additional comments
we want to be sure not to add back labels which were explicitly removed.
* issue_label_predictor should filter out labels which have already …
> LabelBot should take into account all comments on an issue.

- kubeflow_clusters/issue-label-bot/tekton/tekton-dashboard-virtual-service.yaml
- kubeflow_clusters/issue-label-bot/tekton/tekton-dashboard.yaml
- kubeflow_clusters/issue-label-bot/tekton/tekton-triggers.yaml
- kubeflow_clusters/issue-label-bot/tekton/tekton.release.yaml
* We want to use Tekton to build CD pipelines
* Yamls are just the result of checking a copy of the released YAMls
https://github.com/tektoncd/triggers/blob/master/docs/install.md
* Tekton is available at: https://issue-label-bot.endpoints.issue-label-bot-dev.cloud.goog/tekton/#/pipelineruns
> Install tekton, tekton dashboard and tekton triggers on issue-label-bot-dev

- Label_Microservice/auto-update/base/kustomization.yaml
- Label_Microservice/go/cmd/automl/pkg/server/server.go
- Label_Microservice/labelbot-diff.image.json
- acm-repos/issue-label-bot/namespaces/label-bot-prod/apps_v1_deployment_labelbot-diff.yaml
* It is NeedsTraining not NeedsSync that needs to check whether there is
a training job running.
Related to #178
> Fix bug checking if training is running.
