Issue-Embeddings/deployment/certificate-gh-issue-labeler-com.yaml
Issue-Embeddings/deployment/ingress.yaml
Issue-Embeddings/notebooks/09_LangModel_API_Demo.ipynb

Just a naming change, so it doesn't cause confusion in the future
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/code-intelligence/7)

Change endpoint of microservice to embeddings.gh-issue-labeler.com

---

Issue-Embeddings/flask_app/app.py
Issue-Embeddings/flask_app/templates/index.html

https://embeddings.gh-issue-labeler.com
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/code-intelligence/8)

added landing page

---

Issue-Embeddings/flask_app/inference.py
Issue-Embeddings/notebooks/Get-GitHub-Issues.ipynb
README.md

Notebook shows you how to get issues, 
Getting the embeddings en-masse is kind of slow so needs to be moved onto the GPU
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/code-intelligence/14)

Get Issue Data

---

py/Pipfile
py/Pipfile.lock
py/code_intelligence/graphql.py

1. Minor correction to error message
2. Checked in pipenv files for dependency management
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/code-intelligence/27)

added package files

---

Issue-Embeddings/flask_app/inference.py
Issue-Embeddings/notebooks/04b_Inference-Batch.ipynb

I added more utilities to make the process of inference easier, especially in the scenario where you need to generate features from a large amount of issues at a time.  
@abcdefgs0324 you will enjoy the `df_to_emb` method
/assign @abcdefgs0324 @jlewi 
I will move this outside into /py in a future pull request
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/code-intelligence/28)

Utility that allows for Pandas.DataFrame -> Embedding Matrix in Batch

---

Label_Microservice/notebooks/repo_mlp.ipynb
Label_Microservice/requirements.txt

Use kubeflow metadata to store model artifacts while we train models.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/code-intelligence/42)

Store model artifacts while training models

---

Label_Microservice/deployment/Dockerfile.worker
Label_Microservice/deployment/README.md
Label_Microservice/deployment/deployments-test.yaml
Label_Microservice/deployment/deployments.yaml
Label_Microservice/scripts/bootstrap
Label_Microservice/scripts/bootstrap_test

This PR
- adds Dockerfile to build images for workers
- adds deployment yaml files for production and testing cluster
- adds scripts to build images and push them to GCR
- adds readme
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/code-intelligence/46)

Add files to configure the label microservice

---

Issue_Embeddings/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/code-intelligence/48)

Updated README.md

---

Issue_Embeddings/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/code-intelligence/49)

Cleanup README.md

---

py/code_intelligence/gcs_util.py
py/code_intelligence/pubsub_util.py
py/label_microservice/worker.py

- Add gcs and pubsub utils which can be reused later.
- Update workers 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/code-intelligence/47)

Code refactoring to add gcs & pubsub utils

---

OWNERS

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/code-intelligence/57)

Add zhenghuiwang as reviewer

---

py/issue_triage/triage.py

Related to #64
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/code-intelligence/73)

Take into account platform label.

---

Issue_Triage/requirements.txt

Related to #114
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/code-intelligence/115)

Add PyJWT to the triage action image to fix the action.

---

.gitignore
Label_Microservice/.build/prod/extensions_v1beta1_deployment_label-bot-worker.yaml
Label_Microservice/.build/prod/~g_v1_service_label-bot-worker.yaml
Label_Microservice/Makefile
Label_Microservice/deployment/overlays/dev/kustomization.yaml
Label_Microservice/deployment/overlays/prod/kustomization.yaml
Label_Microservice/deployment/requirements.worker.txt
Label_Microservice/developer_guide.md
Label_Microservice/docs/logging_and_monitoring.md
Label_Microservice/notebooks/automl.ipynb
py/code_intelligence/github_util.py
py/code_intelligence/github_util_test.py
py/label_microservice/automl_model.py
py/label_microservice/automl_model_test.py
py/label_microservice/cli.py
py/label_microservice/combined_model.py
py/label_microservice/issue_label_predictor.py
py/label_microservice/models.py
py/label_microservice/universal_kind_label_model.py
py/label_microservice/worker.py

Create an AutoML Model class to generate predictions using AutoML.
* Create a new class/module automl_model to generate predictions
using AutoML models
* Change the function signature of predict_labels to include org and repo
because we want org and repo to be features because they can be highly
informative.
* Also change predict_issue_labels to take in a list of strings for the
body text because in follow on PRs we will start taking into additional
comments and not just the first one.
* Define github_util.build_issue_doc to construct a text document
out of the various features.
Testing
* Dev instance successfully used AutoML model.
https://github.com/kubeflow/code-intelligence/issues/131#issuecomment-622616399
* Check in hydrated configs for prod.
* prod has also been updated and looks …

Use the AutoML Model and the universal model to generate predictions.

---

Issue_Triage/notebooks/metrics.ipynb

* Update the search query with some timestamp parameters so we
can restrict stats to recently updated/labeled issues.

Update issue triage notebook so we can compute metrics for recent issues

---

Label_Microservice/auto-update/base/service-account.yaml
Label_Microservice/ssh-secret/base/kustomization.yaml
tekton/pipelines/update-model-pr-pipeline.yaml
tekton/tasks/update-model-pr-task.yaml

* Update the continuous delivery pipeline to run prctl to create
the PR
* kubeflow/code-intelligence#155

Tekton pipeline to update the model should create the PR

---

kubeflow_clusters/issue-label-bot/certmanager/cert-manager.yaml

Add certmanager configs for label-bot-dev cluster.

---

Label_Microservice/notebooks/automl.ipynb
Label_Microservice/requirements.train.txt
acm-repos/issue-label-bot/namespaces/label-bot-prod/tekton.dev_v1beta1_pipeline_run-notebook.yaml
acm-repos/issue-label-bot/namespaces/label-bot-prod/tekton.dev_v1beta1_task_run-notebook.yaml
tekton/pipeline-runs/train-label-model.yaml
tekton/pipelines/kustomization.yaml
tekton/pipelines/run-notebook-pipeline.yaml
tekton/tasks/kustomization.yaml
tekton/tasks/run-notebook-task.yaml

* Add a parameter to the notebook so that we can optionally not block
on waiting for the model to deploy.
* Cleanup automl notebook.
* Add Tekton resources to run notebook.
* Add a requirements.train.txt to install the dependencies needed to
run the notebook.
Add max_age_days as a parameter.
Successful run:
https://storage.googleapis.com/issue-label-bot-dev_public/label-bot/training/runs/20200723-174527/automl.html
Related to #155

Tekton pipeline to run training.

---

Label_Microservice/auto-update/base/deployment.yaml
Label_Microservice/auto-update/base/kustomization.yaml
Label_Microservice/auto-update/prod/kustomization.yaml
Label_Microservice/auto-update/prod/modelsync.yaml
Label_Microservice/auto-update/prod/retrain-model.yaml
Label_Microservice/go/cmd/automl/main.go
Label_Microservice/go/cmd/automl/pkg/automl/automl.go
Label_Microservice/go/cmd/automl/pkg/server/server.go
Label_Microservice/labelbot-diff.image.json
acm-repos/issue-label-bot/namespaces/label-bot-prod/apps_v1_deployment_labelbot-diff.yaml
acm-repos/issue-label-bot/namespaces/label-bot-prod/automl.cloudai.kubeflow.org_v1alpha1_modelsync_labelbot-deploy.yaml
acm-repos/issue-label-bot/namespaces/label-bot-prod/automl.cloudai.kubeflow.org_v1alpha1_modelsync_labelbot-train.yaml
tekton/pipeline-runs/train-label-model.yaml

* Add a function to compute whether we need to retrain the model
based on age.
* Add a modelsync object.
Related to #155

Run the pipeline to train the model if it is too old.

---

Label_Microservice/auto-update/base/kustomization.yaml
Label_Microservice/deployment/README.md
Label_Microservice/go/cmd/automl/main.go
Label_Microservice/go/cmd/automl/pkg/automl/automl.go
Label_Microservice/go/cmd/automl/pkg/server/server.go
Label_Microservice/labelbot-diff.image.json
acm-repos/issue-label-bot/namespaces/label-bot-prod/apps_v1_deployment_labelbot-diff.yaml
acm-repos/issue-label-bot/namespaces/label-bot-prod/automl.cloudai.kubeflow.org_v1alpha1_modelsync_labelbot-train.yaml

* NeedsSync needs to check whether there is a model being trained or
if there is a dataset being imported. Otherwise we end up launching
multiple overlapping jobs because it takes a long time for the model
to train. During which time the Tekton job will have finished.
* Related to #178

LabelBot NeedSync needs to check if model is being trained.

---

Label_Microservice/notebooks/automl.ipynb
acm-repos/issue-label-bot/namespaces/label-bot-prod/tekton.dev_v1beta1_task_run-notebook.yaml
tekton/tasks/run-notebook-task.yaml

* Related to #185; builds were failing using the existing images; there was a
problem installing papermill.

Upgrade jupyter image for continuous training.

---

Label_Microservice/Makefile
Label_Microservice/auto-update/base/kustomization.yaml
Label_Microservice/go/cmd/automl/main.go
Label_Microservice/go/cmd/automl/pkg/automl/automl.go
Label_Microservice/go/cmd/automl/pkg/server/server.go
Label_Microservice/labelbot-diff.image.json
Makefile
acm-repos/issue-label-bot/namespaces/label-bot-prod/apps_v1_deployment_labelbot-diff.yaml
acm-repos/issue-label-bot/namespaces/label-bot-prod/tekton.dev_v1beta1_task_clone-modify-pr.yaml
tekton/Kptfile
tekton/README.md
tekton/pipeline-runs/train-label-model.yaml
tekton/pipelines/run-notebook-pipeline.yaml
tekton/tasks/run-notebook-task.yaml
tekton/tasks/update-model-pr-task.yaml

* Run deploy as part of the update step and look at all trained models
* This way if the notebook failed after training ran but before model
was deployed we will still run.
* Add a GoCmd to deploy the model
* NeedsSync should take into account undeployed models and then we can
deploy the model.
* Add a CLI command to get operations.
Related to #185

Deploy models as part of autodeployment

---

kubeflow_clusters/issue-label-bot/gcp_config/Makefile
kubeflow_clusters/issue-label-bot/gcp_config/cluster-kubeflow.yaml
kubeflow_clusters/issue-label-bot/gcp_config/cluster.jinja

Part of https://github.com/kubeflow/testing/issues/851

chore(gcp): e2 migration
